{
  "hash": "acb344d6b4577aa55c34899456f5d4f1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Data Analysis and Visualization\"\nsubtitle: \"A Question-and-Answer Approach\"\ndescription: |\n  This project focuses on analyzing a modified autism dataset using R, with a specific emphasis on data preprocessing, univariate statistics, and visualizations. The dataset contains attributes of children who were tested for autism, and the project is structured as a question-and-answer tutorial. Each section addresses different analytical tasks, such as cleaning data, generating descriptive statistics, creating visualizations, and performing hypothesis testing. The tutorial is designed to guide users through the process of exploring the dataset, interpreting results, and applying statistical methods to answer key questions related to autism diagnosis and its associated factors.\ndate: \"08-14-2024\"\ncategories: \n  - Data Analysis\n  - R\n  - Visualisatiom\nimage: autism.png\nformat: \n  html:\n    fig-cap-location: bottom\n    include-before-body: ../../html/margin_image.html\n    include-after-body: ../../html/blog_footer.html\n    page-layout: full # custom #article,\n    code-fold: false\n    code-tools: true\n    df-print: paged\n    smooth-scroll: true\n#    link-external-icon: true\n#    link-external-newwindow: true\n#editor: visual\neditor: \n  markdown: \n    wrap: sentence\nexecute:\n  error: true\n#  eval: false\n  echo: true #fenced\n  freeze: auto\nknitr:\n  opts_chunk:\n    comment: \"#>\"\n    #collapse: true\n    tidy: 'styler'\n    message: false\n    warning: false\n    wrap: true\n\nresources: \n  - \"autism.png\"\ntwitter-card:\n  title: \"Data Analysis and Visualization: A Question-and-Answer Approach\"\n  image: \"autism.png\"\n  image-width: \"1280\"\n  image-height: \"720\"\nopen-graph:\n  title: \"Data Analysis and Visualization: A Question-and-Answer Approach\"\n  image: \"autism.png\" \n  image-width: \"1280\"\n  image-height: \"720\"    \neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n# Project Instructions\n\nYou will work with the `child.csv` file, which is a modified dataset adapted from the autism dataset available on [Kaggle](https://www.kaggle.com). This dataset contains attributes/variables for several children who were tested for autism.\n\nYour task is to perform the following data analysis activities using R. If any data preparation steps cannot be accomplished using R, describe your alternative approach and complete the rest of the analysis in R.\n\n## Autism Data\n\nTo follow along with this tutorial, you can download the dataset below:\n\n\n\n::: {.cell}\n\n:::\n\n\n\n# Import Required Packages\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| label: r-packages\n#| include: true\n\n# Ensure your computer is connected to the internet!\n\npackages_needed <- c(\n  \"tidyverse\", \"vtable\", \"inspectdf\", \"knitr\",\n  \"kableExtra\", \"gt\", \"patchwork\", \"treemap\"\n)\n\nif (!require(install.load)) {\n  install.packages(\"install.load\")\n}\n\ninstall.load::install_load(packages_needed)\ntheme_set(theme_bw())\n```\n:::\n\n\n\n# Import the Dataset\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchild_data <- read_csv(\"child.csv\")\n```\n:::\n\n\n\n## Data Preprocessing\n\nThis step cleans the dataset by removing any white spaces and apostrophes from character variables.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean_data <- child_data %>%\n  mutate_if(is.character, ~ str_squish(str_remove_all(., pattern = \"'\"))) %>%\n  mutate_at(vars(5:11), as.factor)\n```\n:::\n\n\n\n## Descriptive Analysis\n\nYou can generate a detailed summary of the dataset variables using `vtable`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlabel <- data.frame(\n  score = \"A numeric value from the standard tests for autism\",\n  score2 = \"A numeric value from alternative (non-standard) tests for autism\",\n  age = \"The child’s age\",\n  cost = \"Total cost of testing the child (in pounds)\",\n  gender = \"Gender (male or female)\",\n  ethnicity = \"Child’s ethnicity\",\n  jaundice = \"Whether the child was born with jaundice\",\n  autismFH = \"Family history of autism\",\n  residence = \"Country of residence\",\n  relation = \"Who completed the test for the child\",\n  autism = \"Autism diagnosis (YES or NO)\"\n)\n\nvtable(clean_data, labels = label, factor.limit = 5)\n```\n:::\n\n\n\n![](data_description.png)\n\n> **Autism Dataset Overview**\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nclean_data %>%\n  inspect_na() %>%\n  show_plot()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/check_na-1.png){width=480}\n:::\n:::\n\n\n\n## Question 1 \n\n### Task\n\nProduce a plot showing the relative proportion of children residing in Australia, Germany, Italy, and India. Provide comments on your visualization and suggest an alternative plot that could represent this data, noting its advantages. There is no need to create the alternative plot.\n\n### Solution\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat1 <- clean_data %>%\n  filter(residence %in% c(\"Australia\", \"Germany\", \"Italy\", \"India\")) %>%\n  count(residence) %>%\n  mutate(prop = n / sum(n))\n\ndat1 %>%\n  gt() %>%\n  tab_spanner(label = \"Statistics\", columns = vars(n, prop))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"vzqoeahvip\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vzqoeahvip table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vzqoeahvip thead, #vzqoeahvip tbody, #vzqoeahvip tfoot, #vzqoeahvip tr, #vzqoeahvip td, #vzqoeahvip th {\n  border-style: none;\n}\n\n#vzqoeahvip p {\n  margin: 0;\n  padding: 0;\n}\n\n#vzqoeahvip .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vzqoeahvip .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vzqoeahvip .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vzqoeahvip .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vzqoeahvip .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vzqoeahvip .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vzqoeahvip .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vzqoeahvip .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vzqoeahvip .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vzqoeahvip .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vzqoeahvip .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vzqoeahvip .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vzqoeahvip .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vzqoeahvip .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vzqoeahvip .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vzqoeahvip .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vzqoeahvip .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vzqoeahvip .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vzqoeahvip .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vzqoeahvip .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vzqoeahvip .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vzqoeahvip .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vzqoeahvip .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vzqoeahvip .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vzqoeahvip .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vzqoeahvip .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vzqoeahvip .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vzqoeahvip .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vzqoeahvip .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vzqoeahvip .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vzqoeahvip .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vzqoeahvip .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vzqoeahvip .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vzqoeahvip .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vzqoeahvip .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vzqoeahvip .gt_left {\n  text-align: left;\n}\n\n#vzqoeahvip .gt_center {\n  text-align: center;\n}\n\n#vzqoeahvip .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vzqoeahvip .gt_font_normal {\n  font-weight: normal;\n}\n\n#vzqoeahvip .gt_font_bold {\n  font-weight: bold;\n}\n\n#vzqoeahvip .gt_font_italic {\n  font-style: italic;\n}\n\n#vzqoeahvip .gt_super {\n  font-size: 65%;\n}\n\n#vzqoeahvip .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vzqoeahvip .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vzqoeahvip .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vzqoeahvip .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vzqoeahvip .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vzqoeahvip .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vzqoeahvip .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"residence\">residence</th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"Statistics\">\n        <span class=\"gt_column_spanner\">Statistics</span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"prop\">prop</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"residence\" class=\"gt_row gt_center\">Australia</td>\n<td headers=\"n\" class=\"gt_row gt_right\">23</td>\n<td headers=\"prop\" class=\"gt_row gt_right\">0.33823529</td></tr>\n    <tr><td headers=\"residence\" class=\"gt_row gt_center\">Germany</td>\n<td headers=\"n\" class=\"gt_row gt_right\">1</td>\n<td headers=\"prop\" class=\"gt_row gt_right\">0.01470588</td></tr>\n    <tr><td headers=\"residence\" class=\"gt_row gt_center\">India</td>\n<td headers=\"n\" class=\"gt_row gt_right\">42</td>\n<td headers=\"prop\" class=\"gt_row gt_right\">0.61764706</td></tr>\n    <tr><td headers=\"residence\" class=\"gt_row gt_center\">Italy</td>\n<td headers=\"n\" class=\"gt_row gt_right\">2</td>\n<td headers=\"prop\" class=\"gt_row gt_right\">0.02941176</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\ndat1 %>%\n  ggplot(aes(x = reorder(residence, prop), y = prop, fill = residence)) +\n  geom_col(width = 0.5, show.legend = FALSE) +\n  theme_bw() +\n  labs(x = \"Residence\", y = \"Relative Proportion\") +\n  scale_y_continuous(labels = scales::percent)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=480}\n:::\n:::\n\n\n\nThe visualization indicates that most children in this subset reside in India. An alternative visualization could be a pie chart.\n\n**Advantages of a Pie Chart:**\n\n- Simple and easy to interpret\n- Visually clear, especially with few categories\n- Ideal for presenting proportions\n\n## Question 2 \n\n### Task\n\nUse univariate statistics to describe at least the first four attributes. Discuss any notable results, and use visualizations where appropriate.\n\n### Solution: Part 1\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_box <- function(df, cols, col_x = \"autism\") {\n  for (col in cols) {\n    p <- ggplot(df, aes(x = .data[[col_x]], y = .data[[col]], fill = .data[[col_x]])) +\n      geom_boxplot(\n        show.legend = FALSE, width = 0.2, outlier.size = 1,\n        outlier.shape = 5, outlier.colour = \"purple\"\n      ) +\n      scale_fill_manual(values = c(\"YES\" = \"red\", \"NO\" = \"green\")) +\n      labs(y = col, x = NULL, title = paste0(\"Boxplot of \", col, \" by autism status\")) +\n      theme(\n        axis.text.x = element_text(face = \"bold\"),\n        axis.title.y = element_text(size = 12, face = \"bold\")\n      )\n    print(p)\n  }\n}\n\nnum_cols <- clean_data %>%\n  select_if(is.numeric) %>%\n  colnames()\n\nplot_box(clean_data, num_cols)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-4.png){width=672}\n:::\n:::\n\n\n\nBox plots help assess whether a feature is useful in distinguishing between children with and without autism. Here, the cost of testing is higher for children diagnosed with autism, and both test scores are higher in children with autism.\n\n### Solution: Part 2\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_bars <- function(df, cat_cols, facet_var) {\n  for (col in cat_cols) {\n    p <- ggplot(df, aes(x = .data[[col]], fill = .data[[col]])) +\n      geom_bar(show.legend = FALSE, width = 0.3) +\n      labs(\n        x = col, y = \"Number of Children\",\n        title = str_c(\"Bar Plot of \", col),\n        subtitle = paste0(\"Faceted by Autism Status\")\n      ) +\n      facet_wrap(vars({{ facet_var }}), scales = \"free_y\") +\n      theme(\n        axis.title.y = element_text(size = 12, face = \"bold\"),\n        axis.title.x = element_text(size = 12, face = \"bold\"),\n        axis.text.x = element_text(angle = 45, hjust = 1, face = \"bold\")\n      )\n    print(p)\n  }\n}\n\ncat_cols <- clean_data %>%\n  select_if(is.factor) %>%\n  colnames()\n\ncat_cols <- cat_cols[-c(5, 7)] # Removing the class label\n\nplot_bars(clean_data, cat_cols, autism)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-5.png){width=672}\n:::\n:::\n\n\n\nThese plots show that features like `relation`, `autismFH`, `jaundice`, `ethnicity`, and `gender` have significant differences in their distribution based on autism status.\n\n## Question 3 \n\n### Task 3a\n\n- Is the mean score different for children with autism compared to those without, using a significance level of 0.05?\n\n- Is there a difference of at least 1 in mean scores between children with a family history of autism and those without?\n\n### Solution 3a\n\n**Part 1: Testing Variance Homogeneity**\n\nThe statistical hypotheses are:\n\n- **Null Hypothesis** ($H_0$): The variances of the two groups are equal.\n\n- **Alternative Hypothesis** ($H_a$): The variances are different.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::leveneTest(score ~ autism, data = clean_data)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"F value\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1\",\"2\":\"9.44288\",\"3\":\"0.002321208\",\"_rn_\":\"group\"},{\"1\":\"290\",\"2\":\"NA\",\"3\":\"NA\",\"_rn_\":\"\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n**Interpretation**: The p-value is less than 0.05, indicating a significant difference in variances.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(score ~ autism, data = clean_data, alternative = \"two.sided\", var.equal = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tWelch Two Sample t-test\n#> \n#> data:  score by autism\n#> t = -24.242, df = 280.24, p-value < 2.2e-16\n#> alternative hypothesis: true difference in means between group NO and group YES is not equal to 0\n#> 95 percent confidence interval:\n#>  -4.217497 -3.584006\n#> sample estimates:\n#>  mean in group NO mean in group YES \n#>          4.510596          8.411348\n```\n\n\n:::\n:::\n\n\n\nThere is a significant difference in mean scores between children with autism (M = 8.\n\n41, SD = 1.19) and those without (M = 4.51, SD = 1.54); t(280.24) = 24.242, p < 0.05.\n\n**Part 2: Testing Family History**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::leveneTest(score ~ autismFH, data = clean_data)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"F value\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1\",\"2\":\"1.51216\",\"3\":\"0.2198064\",\"_rn_\":\"group\"},{\"1\":\"290\",\"2\":\"NA\",\"3\":\"NA\",\"_rn_\":\"\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n**Interpretation**: The p-value is greater than 0.05, indicating no significant difference in variances.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(score ~ autismFH, data = clean_data, alternative = \"two.sided\", var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tTwo Sample t-test\n#> \n#> data:  score by autismFH\n#> t = 1.3311, df = 290, p-value = 0.1842\n#> alternative hypothesis: true difference in means between group no and group yes is not equal to 0\n#> 95 percent confidence interval:\n#>  -0.2384339  1.2348058\n#> sample estimates:\n#>  mean in group no mean in group yes \n#>          6.477778          5.979592\n```\n\n\n:::\n:::\n\n\n\nThere is no significant difference in mean scores between children with a family history of autism (M = 5.98, SD = 2.60) and those without (M = 6.48, SD = 2.35); t(290) = -1.3311, p = 0.1842.\n\n### Task 3b\n\n- Predict the alternative score (score2) for a child with a standard score of 7.\n- Predict the alternative score (score2) for a child with a standard score of 12.\n\n### Solution 3b\n\n**Part 1:**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(score2 ~ score, data = clean_data)\n\npredict(model, data.frame(score = 7))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>        1 \n#> 7.007971\n```\n\n\n:::\n:::\n\n\n\n$score2 = 7.01$\n\n**Part 2:**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(model, data.frame(score = 12))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>        1 \n#> 11.98049\n```\n\n\n:::\n:::\n\n\n\n$score2 = 11.98$\n\n## Question 4 \n\n### Task\n\nCreate a dataset containing all the data in `child.csv` plus a new column `ageGroup` with values \"Five and under\" and \"6 and over.\" Compare the standard score against the cost for each age group, and show whether there was a family history of autism. Comment on your visualizations.\n\n### Solution\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean_data <- clean_data %>%\n  mutate(ageGroup = case_when(age >= 6 ~ \"6 and over\", TRUE ~ \"Five and under\"))\n\nclean_data %>%\n  ggplot(aes(x = cost, y = score, color = ageGroup)) +\n  geom_line() +\n  facet_grid(ageGroup ~ autismFH, scales = \"free\") +\n  labs(title = \"Cost vs. Score by Age Group and Family History of Autism\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\nChildren aged five years and under with a family history of autism tend to have lower costs associated with standard autism testing.\n\n## Question 5 \n\n### Task\n\nDiscuss the following statement using a maximum of three plot examples to illustrate your explanations (Word limit: 300 words):\n\nThere are different methods of displaying data, with no single method being suitable for all data types. Some visualizations effectively convey the intended information, while others fail. The data-ink ratio and lie factor also contribute to the quality of a visualization.\n\nNote: Your plot examples must relate to the `child.csv` dataset.\n\n### Solution: Part 1\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- clean_data %>%\n  ggplot(aes(x = score)) +\n  geom_histogram(binwidth = 5, fill = \"dark blue\") +\n  labs(title = \"Histogram\")\n\np2 <- clean_data %>%\n  ggplot(aes(y = score)) +\n  geom_boxplot(fill = \"dark blue\") +\n  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) +\n  labs(title = \"Boxplot\")\n\np3 <- clean_data %>%\n  ggplot(aes(x = score)) +\n  geom_dotplot(binwidth = 0.23, stackratio = 1, fill = \"blue\", stroke = 2) +\n  scale_y_continuous(NULL, breaks = NULL) +\n  labs(title = \"Dot Plot\")\n\np1 / (p2 + p3) + plot_annotation(title = \"Different Plots for Standard Test Scores\")\n```\n:::\n\n\n\n![](Q5a.png)\n\nHistograms and boxplots are common for showing the distribution of continuous variables. Dot plots, though suitable for smaller datasets, can become cluttered with more data. When dealing with large datasets, boxplots or histograms are more effective.\n\n### Solution: Part 2\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- clean_data %>%\n  count(relation) %>%\n  ggplot(aes(x = reorder(relation, n), y = n, fill = relation)) +\n  geom_col(width = 0.4, show.legend = FALSE) +\n  labs(title = \"Bar Chart\", x = \"\")\n\np2 <- clean_data %>%\n  select(relation) %>%\n  count(relation) %>%\n  ggplot(aes(x = reorder(relation, n), y = n)) +\n  geom_segment(aes(xend = relation, yend = 0)) +\n  geom_point(size = 6, color = \"orange\") +\n  theme_bw() +\n  xlab(\"\")\n\np3 <- clean_data %>%\n  select(relation) %>%\n  count(relation) %>%\n  treemap(index = \"relation\", vSize = \"n\", title = \"Treemap\")\n\np4 <- pie(\n  table(clean_data$relation),\n  col = c(\"purple\", \"violetred1\", \"green3\", \"cornsilk\"),\n  radius = 0.9,\n  main = \"Pie Chart\"\n)\n```\n:::\n\n\n\n![](Q5b.png)\n\nPie charts can be less effective when dealing with multiple categories, as they require interpreting angles and comparing non-adjacent slices. Bar charts or treemaps may be more effective in such cases.\n\n## Question 6\n\n### Task\n\nAssume you have an additional 19 independent datasets with the same number of observations about children tested for autism. Load the `independent_data.csv` dataset, which includes the distribution for the attribute `autism`, and demonstrate that the size of the confidence intervals for the average percentage of positive cases of autism increases as the confidence level increases (90%, 95%, 98%). Discuss any improvements that could enhance your demonstration.\n\n### Solution\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanother_dataset <- read_csv(\"blog/data-analysis-and-visualization/independent_dataset.csv\")\n```\n\n::: {.cell-output .cell-output-error}\n\n```\n#> Error: 'blog/data-analysis-and-visualization/independent_dataset.csv' does not exist in current working directory ('C:/Users/admin/Desktop/gbganalyst.github.io/blog/data-analysis-and-visualization').\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Function to calculate the size of confidence intervals\nconf.size <- function(dataset, level = 0.90) {\n  t_test <- t.test(dataset[, 2] %>% pull(), conf.level = level)\n  print(t_test$conf.int)\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nconf.size(another_dataset, level = 0.9)\n```\n\n::: {.cell-output .cell-output-error}\n\n```\n#> Error in eval(expr, envir, enclos): object 'another_dataset' not found\n```\n\n\n:::\n:::\n\n\n\nThe 90% confidence interval for the average percentage of positive cases of autism ranges from 48.42% to 50.42%.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconf.size(another_dataset, level = 0.95)\n```\n\n::: {.cell-output .cell-output-error}\n\n```\n#> Error in eval(expr, envir, enclos): object 'another_dataset' not found\n```\n\n\n:::\n:::\n\n\n\nThe 95% confidence interval for the average percentage of positive cases of autism ranges from 48.20% to 50.64%.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconf.size(another_dataset, level = 0.98)\n```\n\n::: {.cell-output .cell-output-error}\n\n```\n#> Error in eval(expr, envir, enclos): object 'another_dataset' not found\n```\n\n\n:::\n:::\n\n\n\nThe 98% confidence interval for the average percentage of positive cases of autism ranges from 47.94% to 50.90%.\n\n> **Overall Interpretation**\n\nAs the confidence level increases, the confidence intervals become wider, making it harder to reject the null hypothesis.\n\n---\n\n![Congratulations!](https://media2.giphy.com/media/LXiElF2dzvUmQ/giphy.gif)\n\n---\n\nI hope you found this tutorial helpful. For more updates on data science with R, Python, and Excel, follow me on [Twitter](https://www.twitter.com/gbganalyst) and [LinkedIn](https://www.linkedin.com/in/ezekiel-ogundepo). The GitHub repository for this tutorial is available [here](https://github.com/gbganalyst/Data-Visualization-and-Analysis).\n\n![Cheers!](https://media2.giphy.com/media/Tw4z4MD34y11K/giphy.gif)\n```\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}